#!/bin/bash
# Automatically set Git config values from parent folders.
# See https://stackoverflow.com/a/39759416/2747593

dir=$(pwd)
while [ "$dir" != "/" ]
do
  # First directory would be the new Git repo, so skip it.
  dir=$(dirname $dir)
  if [ -f $dir/.gitconfig ]
  then
    for config in $(git config --file $dir/.gitconfig --list)
    do
      var=$(echo $config | cut -d = -f 1)
      value=$(echo $config | cut -d = -f 2)
      actual=$(git config $var)
      if [ "$actual" != "$value" ]
      then
        git config $var $value
      fi
    done
  fi
done
